### ISSUE TITLE
Better date recognition using Recognizers-Text

### ISSUE THREAD

**Issue by iMicknl** [nzregs/receipt-api#1]
I just came across this repository, nice work & nicely written down! I was working on something similar built in NodeJS, using almost the same strategy. However I have a suggestion which you can use for better date recognition. 

In order to retrieve the DateTime, you could make use of [Recognizers-Text](https://github.com/Microsoft/Recognizers-Text). Especially since the datetime can be in many different formats, which can be parsed easily using the Recognizers.

**Comment by nzregs** [comment]
Great suggestion!  I've not used that, and i went 'quick and dirty' on the regex with this. I'll have to take a look and maybe come back and update if i get a chance.
